# -*- coding: utf-8 -*-
"""
Created on Mon Mar 15 20:13:19 2021

@author: Dillon Mazerolle
"""

'''Below represents the base expense categories and corresponding expense type.
This list is added to the local database upon first use of the program.
The user may add/delete new categories based on their preferences'''
base_expense_type = [('charitable', 'variable'),
                    ('consumer_purchases', 'variable'),
                    ('Education', 'variable'),
                     ('groceries', 'variable'),
                     ('housing_extras', 'fixed'),
                     ('medical', 'variable'),
                     ('misc_transfers', 'other'),
                     ('taxes_fees', 'fixed'),
                     ('income', 'revenue'),
                     ('insurance', 'fixed'),
                     ('investments', 'savings'),
                     ('it', 'fixed'),
                     ('pets', 'variable'),
                     ('quick_food', 'variable'),
                     ('rent_mortgage', 'fixed'),
                     ('social', 'variable'),
                     ('sports_fitness', 'variable'),
                     ('transportation', 'fixed'),
                     ('travel', 'variable')]


'''Below represents the base category dictionary, used in the classification algorithm.
This list is added to the local database upon first use of the program.
The user may add/delete based on their spending patterns.'''
base_categories = [('charitable', 'Movember'),
                 ('charitable', 'REDCROSS'),
                 ('charitable', 'TAKEACTION'),
                 ('charitable', 'united way'),
                 ('consumer_purchases', 'BROWNS CLEANERS'),
                 ('consumer_purchases', 'HUDSONS BAY'),
                 ('consumer_purchases', 'DOLLARAMA'),
                 ('consumer_purchases', 'DAVIDS TEA'),
                 ('consumer_purchases', 'LULULEMON'),
                 ('consumer_purchases', 'BUCK TWO'),
                 ('consumer_purchases', 'BOUCLAIR'),
                 ('consumer_purchases', 'MAKER HOUSE'),
                 ('consumer_purchases', 'NORDSTROM'),
                 ('consumer_purchases', 'ROOTS'),
                 ('consumer_purchases', 'ARITZIA'),
                 ('consumer_purchases', 'PLAYSTATION'),
                 ('consumer_purchases', 'BROWNS RIDEAU'),
                 ('consumer_purchases', 'ABERCROMBIE'),
                 ('consumer_purchases', 'URBAN OUTFITTERS'),
                 ('consumer_purchases', 'CAPITAL HOME HARDWARE'),
                 ('consumer_purchases', 'STAPLES STORE'),
                 ('consumer_purchases', 'EB GAMES'),
                 ('consumer_purchases', 'ZARA'),
                 ('consumer_purchases', 'MAGPIE JEWELLERY'),
                 ('consumer_purchases', 'jewel'),
                 ('consumer_purchases', 'CANADIAN TIRE'),
                 ('consumer_purchases', 'CARLTON CARDS'),
                 ('consumer_purchases', 'ETSYCOM'),
                 ('consumer_purchases', 'FLOWERS'),
                 ('consumer_purchases', 'ALDO'),
                 ('consumer_purchases', 'PRESTON PAINT CENTER'),
                 ('consumer_purchases', 'SANCTUARY PAINT'),
                 ('consumer_purchases', 'HOME HARDWARE'),
                 ('consumer_purchases', 'HOMESENSE'),
                 ('consumer_purchases', 'DOLLARAMA'),
                 ('consumer_purchases', 'MICHAELS'),
                 ('consumer_purchases', 'TERRA'),
                 ('consumer_purchases', 'NATURALLYVAIN'),
                 ('consumer_purchases', 'STOKES'),
                 ('consumer_purchases', 'SQ UPTOWN SOX'),
                 ('consumer_purchases', 'LEGO STORE'),
                 ('consumer_purchases', 'THEBAYCOM'),
                 ('consumer_purchases', 'STAPLES'),
                 ('consumer_purchases', 'PRESTON PAINT CENTER'),
                 ('consumer_purchases', 'PARTY CITY'),
                 ('consumer_purchases', 'DECORTORS CHOICE PAINT'),
                 ('consumer_purchases', 'Sony Interactive'),
                 ('consumer_purchases', 'OLDNAVY'),
                 ('consumer_purchases', 'TALISMAN F'),
                 ('consumer_purchases', 'TANGER OUTLETS'),
                 ('consumer_purchases', 'LAST HUNT'),
                 ('consumer_purchases', 'MAC Rideau'),
                 ('consumer_purchases', 'Garmin'),
                 ('consumer_purchases', 'LOWES'),
                 ('consumer_purchases', 'PRESTON HARDWARE'),
                 ('consumer_purchases', 'MASTERCLASS'),
                 ('consumer_purchases', 'PAPER LABEL NORTH'),
                 ('consumer_purchases', 'walmart'),
                 ('consumer_purchases', 'amazon'),
                 ('consumer_purchases', 'amzn'),
                 ('consumer_purchases', 'cloth'),
                 ('consumer_purchases', 'ikea'),
                 ('consumer_purchases', 'structube'),
                 ('consumer_purchases', 'bed bath'),
                 ('consumer_purchases', 'indigo'),
                 ('consumer_purchases', 'saje'),
                 ('consumer_purchases', 'home depot'),
                 ('consumer_purchases', 'chapters'),
                 ('consumer_purchases', 'sephora'),
                 ('consumer_purchases', 'lush'),
                 ('consumer_purchases', 'the bay'),
                 ('consumer_purchases', 'simons'),
                 ('consumer_purchases', 'cdn tire'),
                 ('consumer_purchases', 'wayfair'),
                 ('consumer_purchases', 'SOFTMOC'),
                 ('consumer_purchases', 'SKOG KUST'),
                 ('consumer_purchases', 'NYX'),
                 ('consumer_purchases', 'IMPERIAL BARBER'),
                 ('consumer_purchases', 'BR FACTORY'),
                 ('consumer_purchases', 'VISTAPRINT'),
                 ('consumer_purchases', 'SPA JUNKIE BEAUTY BAR'),
                 ('consumer_purchases', 'GAP CAN'),
                 ('consumer_purchases', 'BODY WORKS'),
                 ('consumer_purchases', 'KIEHLS'),
                 ('consumer_purchases', 'SKECHERS'),
                 ('consumer_purchases', 'HM CA'),
                 ('consumer_purchases', 'OLD NAVY'),
                 ('consumer_purchases', 'PAINT DeCOR'),
                 ('consumer_purchases', 'STEVE MADDEN'),
                 ('consumer_purchases', 'EDDIE BAUER'),
                 ('consumer_purchases', 'CANADIANTIRE'),
                 ('consumer_purchases', 'LE CREUSET'),
                 ('consumer_purchases', 'STERLING GRILLADES'),
                 ('consumer_purchases', 'IROBOT'),
                 ('consumer_purchases', 'SLEEP COUNTRY'),
                 ('consumer_purchases', 'MAKE GREEN FLORIST'),
                 ('consumer_purchases', 'RIDGEWALLET'),
                 ('consumer_purchases', 'GIANT TIGER'),
                 ('consumer_purchases', 'BAYCOM'),
                 ('consumer_purchases', 'LA BAIE'),
                 ('consumer_purchases', 'Bay ST LAURENT'),
                 ('consumer_purchases', 'Bay SCARBOROUGH'),
                 ('consumer_purchases', 'BISSELL'),
                 ('consumer_purchases', 'JOEFRESH'),
                 ('consumer_purchases', 'ALEXANIAN'),
                 ('consumer_purchases', 'AVEDA ONLINE CANADA'),
                 ('consumer_purchases', 'DYSON'),
                 ('consumer_purchases', 'Bay BAYSHORE'),
                 ('consumer_purchases', 'ODDS SODS SHOP'),
                 ('consumer_purchases', 'SENS STORE'),
                 ('consumer_purchases', 'WILLIAMS FOOD EQUIP'),
                 ('Education', 'UNIVERSITY'),
                 ('Education', 'UDEMY'),
                 ('groceries', 'REXALL'),
                 ('groceries', 'METRO'),
                 ('groceries', 'RCSS'),
                 ('groceries', 'SOBEYS'),
                 ('groceries', 'YIG'),
                 ('groceries', 'LOBLAW'),
                 ('groceries', 'NUTRITION HOUSE'),
                 ('groceries', 'LA BOTTEGA'),
                 ('groceries', 'UNREFINED OLI'),
                 ('groceries', 'NATURAL FOOD PANTR '),
                 ('groceries', 'ADONIS'),
                 ('groceries', 'HERB SPICE '),
                 ('groceries', 'ROCHONGARDN'),
                 ('groceries', 'PC EXPRESS'),
                 ('groceries', 'massine'),
                 ('groceries', 'loblaws'),
                 ('groceries', 'independent'),
                 ('groceries', 'COSTCO WHOLESALE'),
                 ('groceries', 'COSTCO CA'),
                 ('groceries', 'farm boy'),
                 ('groceries', 'shoppers'),
                 ('groceries', 'goodfood'),
                 ('groceries', 'ROWE FARM '),
                 ('groceries', 'COBS BREAD'),
                 ('groceries', 'MARCHE'),
                 ('groceries', 'BULK BARN'),
                 ('housing_extras', 'CLEMENT MARCHAND'),
                 ('housing_extras', 'RELIANCE HM'),
                 ('housing_extras', 'APPLIANCE REPAIR'),
                 ('housing_extras', 'hydro'),
                 ('housing_extras', 'enbridge'),
                 ('housing_extras', 'ocscc'),
                 ('housing_extras', 'NUTRILAWN'),
                 ('housing_extras', 'STONEWORKS'),
                 ('housing_extras', 'RITCHIE FEED SEED'),
                 ('housing_extras', 'DEKA HOME'),
                 ('housing_extras', 'TES ROLLOFF'),
                 ('housing_extras', 'ARLO '),
                 ('housing_extras', 'ARTIST CRAFT'),
                 ('medical', 'ADMINBY GWL'),
                 ('misc_transfers', 'DEPOSIT'),
                 ('medical', 'ADMIN CL'),
                 ('misc_transfers', 'ABM Deposit'),
                 ('taxes_fees', 'cash back'),
                 ('medical', 'manuvie'),
                 ('medical', 'gwl'),
                 ('insurance', 'insurance'),
                 ('insurance', 'coughlin'),
                 ('insurance', 'personal'),
                 ('insurance', 'MANULIFE'),
                 ('insurance', 'SUN LIFE'),
                 ('investments', 'tfsa'),
                 ('investments', 'investment'),
                 ('it', 'APLITUNE'),
                 ('it', 'APL ITUNE'),
                 ('it', 'APPLECOM'),
                 ('consumer_purchases', 'spotify'),
                 ('it', 'PARLEZ WIRELESS INC'),
                 ('it', 'rogers'),
                 ('it', 'samsung'),
                 ('it', 'cable'),
                 ('it', 'telus'),
                 ('it', 'apple'),
                 ('it', 'CANADA COMPUTERS'),
                 ('it', 'NETFLIX'),
                 ('it', 'YOUTUBE'),
                 ('it', 'LENOVO'),
                 ('it', 'TERANET'),
                 ('medical', 'CARTE BLANCHE HAUTE'),
                 ('medical', 'NORDIKSPA'),
                 ('medical', 'DENTAL'),
                 ('medical', 'massage'),
                 ('medical', 'EYES GLEBE'),
                 ('medical', 'BONLOOK'),
                 ('medical', 'RENUSPA'),
                 ('medical', 'ASHBY ASSOCIATES'),
                 ('medical', 'hospita'),
                 ('medical', 'CARTE BLANCHE '),
                 ('medical', 'CHIROMED'),
                 ('medical', 'MEDICAL'),
                 ('medical', 'HOSPITOTTAWA'),
                 ('misc_transfers', 'MBCASH ADVANCE'),
                 ('misc_transfers', 'withdrawal'),
                 ('misc_transfers', 'trf'),
                 ('misc_transfers', 'credit card'),
                 ('misc_transfers', 'transfer'),
                 ('misc_transfers', 'visa'),
                 ('misc_transfers', 'draft purchase'),
                 ('misc_transfers', 'party credit'),
                 ('misc_transfers', 'MBDEP'),
                 ('misc_transfers', 'Customer Transfer Dr.'),
                 ('pets', 'pets'),
                 ('pets', 'CANINE'),
                 ('pets', 'Animal H'),
                 ('quick_food', 'DOMINOS'),
                 ('quick_food', 'ZAKS DINERS'),
                 ('quick_food', 'SUBWAY'),
                 ('quick_food', 'MERRY DAIRY'),
                 ('quick_food', 'TERIYAKI SUSHI'),
                 ('quick_food', 'FRESHII'),
                 ('quick_food', 'QUICKIE'),
                 ('quick_food', 'KETTLEMANS'),
                 ('quick_food', 'MCDONALDS'),
                 ('quick_food', 'PURDYS'),
                 ('quick_food', 'PIRHO GRILL'),
                 ('quick_food', 'SUSHI'),
                 ('quick_food', 'MORNING OWL'),
                 ('quick_food', 'COCO FRESH'),
                 ('quick_food', 'GABRIEL PIZZA'),
                 ('quick_food', 'THIMBLE CAKES'),
                 ('quick_food', 'DAIRY QUEEN'),
                 ('quick_food', 'OCCO KITCHEN'),
                 ('quick_food', 'FAVORIS'),
                 ('quick_food', 'PITA PIT'),
                 ('quick_food', 'LITTLE VICTORIES'),
                 ('quick_food', 'MOOSHU'),
                 ('quick_food', 'PURE GELATO'),
                 ('quick_food', 'ICE CREAM'),
                 ('quick_food', 'SUBITO SANDWICH'),
                 ('quick_food', 'THREE TARTS BAKESHOP'),
                 ('quick_food', 'DANISH PASTRY HOUSE'),
                 ('quick_food', 'VOLOS GREEK CUISINE'),
                 ('quick_food', 'GONGFU STREET FOOD'),
                 ('quick_food', 'NOODLE HOUS'),
                 ('quick_food', 'CHATIME'),
                 ('quick_food', 'BOOSTER'),
                 ('quick_food', 'ELGIN STREET DINER'),
                 ('quick_food', 'SANSOTEI RAMEN '),
                 ('quick_food', 'NOSTALIGICA '),
                 ('quick_food', 'SQUISH'),
                 ('quick_food', 'BUBBLE TE'),
                 ('quick_food', 'RAW PULP GRIND'),
                 ('quick_food', 'ELDORADO TACO'),
                 ('quick_food', 'ARTISIN'),
                 ('quick_food', 'ART HOUSE'),
                 ('quick_food', 'RED DOOR'),
                 ('quick_food', 'BAKERY WAKEFIELD'),
                 ('quick_food', 'REAL FRUIT BUBBLE TEA '),
                 ('quick_food', 'CARMELITO'),
                 ('quick_food', 'LES MOULINS LA FAYETTE '),
                 ('quick_food', 'coffee'),
                 ('quick_food', 'cafe'),
                 ('quick_food', 'starbucks'),
                 ('quick_food', 'chartwell'),
                 ('quick_food', 'tim hortons'),
                 ('quick_food', 'second cup'),
                 ('quick_food', 'skipthedishes'),
                 ('quick_food', 'MICHA SALADS'),
                 ('quick_food', 'FPOS COBS BREAD TORON'),
                 ('quick_food', 'GODIVA CHOCOLATIER INC'),
                 ('quick_food', 'SWEET OVEN '),
                 ('quick_food', 'BOULANGERIE'),
                 ('quick_food', 'BASKIN'),
                 ('quick_food', 'JIMMY GREEK'),
                 ('quick_food', 'BLACK WALNUT'),
                 ('quick_food', 'GREEN REBEL'),
                 ('quick_food', 'JOJOS PIZZERIA STITTSVILLE'),
                 ('quick_food', 'HARVEST MOON ORCHARD CARP'),
                 ('quick_food', 'BENNY CO'),
                 ('quick_food', 'C PARADIS'),
                 ('quick_food', 'CHANCES R'),
                 ('quick_food', 'TRATTORIA CAFFE'),
                 ('quick_food', 'NELSON WATER'),
                 ('quick_food', 'PALMIER CHELSEA'),
                 ('quick_food', 'MENUCAFOOD ORDERING'),
                 ('quick_food', 'UNCLE TETSU '),
                 ('quick_food', 'VIA CIBO'),
                 ('rent_mortgage', 'cheque'),
                 ('rent_mortgage', 'mortgage'),
                 ('social', 'LIEUTENANTS PUMP'),
                 ('social', 'WHALESBONE'),
                 ('social', 'BIG RIG'),
                 ('social', 'EL FURNITURE'),
                 ('social', 'HEART CROWN'),
                 ('social', 'BYWARDS LEVEL'),
                 ('social', 'CACTUS CLUB'),
                 ('social', 'BOSTON PIZZA'),
                 ('social', 'JACK ASTORS'),
                 ('social', 'PRESCOTT'),
                 ('social', 'EVOO GREEK'),
                 ('social', 'JOEY'),
                 ('social', 'CULINAIRE'),
                 ('social', 'ROYAL OAK'),
                 ('social', 'MAMMA TERESA'),
                 ('social', 'FOURTH AVENUE WINE'),
                 ('social', 'WEST PARK BOWLING'),
                 ('social', 'CHEZ LUCIEN'),
                 ('social', 'RABBIT HOLE'),
                 ('social', 'MACLARENS ELGIN'),
                 ('social', 'PUREKITCHEN'),
                 ('social', 'NORTH NAVY'),
                 ('social', 'ABSOLUTE COMEDY'),
                 ('social', 'CRUST CRATE'),
                 ('social', 'MILESTONES'),
                 ('social', 'MOXIES'),
                 ('social', 'DARCY MCGEES'),
                 ('social', 'BROWNS SOCIALHOUSE'),
                 ('social', 'CENTRAL BIERHAUS'),
                 ('social', 'SIDEDOOR CONTEMPORARY'),
                 ('social', 'SENS HOUSE'),
                 ('social', 'EL CAMINO'),
                 ('social', 'TWO SIX ATE'),
                 ('social', 'UNION'),
                 ('social', 'PURE KITCHEN'),
                 ('social', 'LIEUTENANTS PUMP'),
                 ('social', 'BIER MARKT'),
                 ('social', 'ROWAN'),
                 ('social', 'FELEENAS'),
                 ('social', 'EVENTBRITE'),
                 ('social', 'VANITEA ROOM'),
                 ('social', 'LANSDOWNE STADIUM'),
                 ('social', 'LOCAL LANSDOWNE'),
                 ('social', 'BLUESFEST'),
                 ('social', 'WINE'),
                 ('social', 'ELMDALE'),
                 ('social', 'ANTHONYS'),
                 ('social', 'FAT RABBIT'),
                 ('social', 'EVENTS NAC'),
                 ('social', 'FRONTGATE TICKETS'),
                 ('social', 'THIRD'),
                 ('social', 'CINEPLEX'),
                 ('social', 'MOSCOW TEA ROOM'),
                 ('social', 'BOOGIE BIRDIE'),
                 ('social', 'FOX FEATHER'),
                 ('social', 'BIAGIOS ITALIAN'),
                 ('social', 'NEXT'),
                 ('social', 'WINE RACK '),
                 ('social', 'AROMA MEZE'),
                 ('social', 'LASER QUEST'),
                 ('social', 'ROCKCLIFFE BOAT'),
                 ('social', 'CHURCHILLS'),
                 ('social', 'RIVIERA'),
                 ('social', 'EL CAMINO '),
                 ('social', 'PUREKTCHEN'),
                 ('social', 'lcbo'),
                 ('social', 'restau'),
                 ('social', 'brew'),
                 ('social', 'beer'),
                 ('social', 'KEG YORK STREET'),
                 ('social', 'JAMES STREET'),
                 ('social', 'DRAFT PUB'),
                 ('social', 'GASTRO'),
                 ('social', 'BARLEY MOW'),
                 ('social', 'CORNERSTONE BAR'),
                 ('social', 'PUB CHELSEA'),
                 ('social', 'PUB ITALIA'),
                 ('social', 'JAMES ST PUB'),
                 ('social', 'HAPPY FISH'),
                 ('social', 'KARAOKE'),
                 ('social', 'HINTONBURG PUBLIC HOUSE'),
                 ('social', 'GOODMAN'),
                 ('social', 'ST LOUIS BAR'),
                 ('social', 'BAR LUPULUS'),
                 ('social', 'SMALL PONY'),
                 ('social', 'JONNY CANUCKS BAR'),
                 ('social', 'CHESHIRE CAT'),
                 ('social', 'THEATR'),
                 ('social', 'LANDMARK'),
                 ('social', 'MANDARIN KANATA'),
                 ('social', 'PACIOLAN'),
                 ('social', 'TICKETMASTER'),
                 ('social', 'POCO PAZZO'),
                 ('social', 'LONE STAR'),
                 ('sports_fitness', 'REEBOK'),
                 ('sports_fitness', 'NEW BALANCE'),
                 ('sports_fitness', 'FRESH AIR EXPERIENCE'),
                 ('sports_fitness', 'HONEYSUCKLE SWIM'),
                 ('sports_fitness', 'PHL'),
                 ('sports_fitness', 'HOCKEY'),
                 ('sports_fitness', 'MOUNT PAKENHAM'),
                 ('sports_fitness', 'CALABOGIE HIGHLANDS'),
                 ('sports_fitness', 'VALIQUETTE SOURCE'),
                 ('sports_fitness', 'ATHLETIC CA'),
                 ('sports_fitness', 'GYM'),
                 ('sports_fitness', 'CYCLE'),
                 ('sports_fitness', 'RUNNING'),
                 ('sports_fitness', 'PEPPERMINT'),
                 ('sports_fitness', 'LA SORCIER'),
                 ('sports_fitness', 'ENDUR APPA'),
                 ('sports_fitness', 'Rapha'),
                 ('sports_fitness', 'ZWIFT'),
                 ('sports_fitness', 'FRESH AIR EXPERIENCE '),
                 ('sports_fitness', 'golf'),
                 ('sports_fitness', 'wheelhouse'),
                 ('sports_fitness', 'sport'),
                 ('sports_fitness', 'mountain'),
                 ('sports_fitness', 'bushtuk'),
                 ('sports_fitness', 'MEC CANADA'),
                 ('sports_fitness', 'bicic'),
                 ('sports_fitness', 'NIKE CANADA'),
                 ('sports_fitness', 'Asics Canada'),
                 ('sports_fitness', 'Decathlon'),
                 ('taxes_fees', 'annual fee'),
                 ('taxes_fees', 'Service Charge'),
                 ('taxes_fees', 'MONTHLY FEE'),
                 ('taxes_fees', 'Overdraft Protect Fee'),
                 ('taxes_fees', 'Overdraft Interest'),
                 ('taxes_fees', 'INTEREST CHARGES'),
                 ('transportation', 'MACEWEN'),
                 ('transportation', 'DRUMMONDS'),
                 ('transportation', 'ONROUTE'),
                 ('transportation', 'TIGER EXPRESS'),
                 ('transportation', 'ULTRAMAR'),
                 ('transportation', 'MRGAS'),
                 ('transportation', 'PIONEER'),
                 ('transportation', 'HUSKY'),
                 ('transportation', 'MR GAS'),
                 ('transportation', 'uber'),
                 ('transportation', 'ford'),
                 ('transportation', 'honda'),
                 ('transportation', 'petro'),
                 ('transportation', 'esso'),
                 ('transportation', 'shell'),
                 ('transportation', 'lube'),
                 ('transportation', 'HUNTMAR'),
                 ('transportation', 'JIFFY'),
                 ('transportation', 'taxi'),
                 ('travel', 'INTERNATIONAL AIRPO'),
                 ('travel', 'PORTER AIR'),
                 ('travel', 'COOP CABS'),
                 ('travel', 'SHERATON'),
                 ('travel', 'HARAR GARAGE'),
                 ('travel', 'AIRSERV'),
                 ('travel', 'AIRBNB'),
                 ('travel', 'BUDGET'),
                 ('travel', 'DELTA'),
                 ('travel', 'YYZ'),
                 ('travel', 'EURO'),
                 ('travel', 'VIA RAIL'),
                 ('travel', 'FLIGHT '),
                 ('travel', 'hotel'),
                 ('travel', 'TRIPADVISOR'),
                 ('travel', 'TRAVEL RETAIL'),
                 ('travel', 'AIRCANADA'),
                 ('travel', 'CAPITAL CRUISES'),
                 ('travel', 'STCO CANADA TRAVEL')]

