# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_v1\resultsForm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1326, 761)
        Form.setStyleSheet("background-color: rgb(162, 240, 200);\n"
"border-color: rgb(12, 12, 12);")
        self.tab_byMonthYear = QtWidgets.QTabWidget(Form)
        self.tab_byMonthYear.setGeometry(QtCore.QRect(10, 40, 621, 561))
        self.tab_byMonthYear.setObjectName("tab_byMonthYear")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tab.setObjectName("tab")
        self.table_byMonth = QtWidgets.QTableWidget(self.tab)
        self.table_byMonth.setGeometry(QtCore.QRect(10, 10, 651, 511))
        self.table_byMonth.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.table_byMonth.setObjectName("table_byMonth")
        self.table_byMonth.setColumnCount(4)
        self.table_byMonth.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_byMonth.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_byMonth.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_byMonth.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_byMonth.setHorizontalHeaderItem(3, item)
        self.tab_byMonthYear.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tab_2.setObjectName("tab_2")
        self.table_byYear = QtWidgets.QTableWidget(self.tab_2)
        self.table_byYear.setGeometry(QtCore.QRect(10, 10, 661, 511))
        self.table_byYear.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.table_byYear.setObjectName("table_byYear")
        self.table_byYear.setColumnCount(4)
        self.table_byYear.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_byYear.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_byYear.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_byYear.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_byYear.setHorizontalHeaderItem(3, item)
        self.tab_byMonthYear.addTab(self.tab_2, "")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(650, 10, 512, 163))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.form_exportData = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.form_exportData.setContentsMargins(0, 0, 0, 0)
        self.form_exportData.setObjectName("form_exportData")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.form_exportData.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cmd_exportData = QtWidgets.QCommandLinkButton(self.formLayoutWidget)
        self.cmd_exportData.setObjectName("cmd_exportData")
        self.form_exportData.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmd_exportData)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.form_exportData.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cbo_catSelectorExporting = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cbo_catSelectorExporting.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbo_catSelectorExporting.setObjectName("cbo_catSelectorExporting")
        self.cbo_catSelectorExporting.addItem("")
        self.form_exportData.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbo_catSelectorExporting)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.form_exportData.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.radio_allTransactions = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radio_allTransactions.setObjectName("radio_allTransactions")
        self.form_exportData.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.radio_allTransactions)
        self.radio_byMonth = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radio_byMonth.setObjectName("radio_byMonth")
        self.form_exportData.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.radio_byMonth)
        self.radio_byYear = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radio_byYear.setObjectName("radio_byYear")
        self.form_exportData.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.radio_byYear)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(650, 200, 732, 249))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.layout_pltGrid = QtWidgets.QGridLayout(self.formLayoutWidget_2)
        self.layout_pltGrid.setContentsMargins(0, 0, 0, 0)
        self.layout_pltGrid.setObjectName("layout_pltGrid")
        self.date_lowRange = QtWidgets.QDateEdit(self.formLayoutWidget_2)
        self.date_lowRange.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.date_lowRange.setObjectName("date_lowRange")
        self.layout_pltGrid.addWidget(self.date_lowRange, 7, 1, 1, 1)
        self.lbl_dateRange_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_dateRange_2.setObjectName("lbl_dateRange_2")
        self.layout_pltGrid.addWidget(self.lbl_dateRange_2, 7, 0, 1, 1)
        self.lbl_scatterYRange = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_scatterYRange.setObjectName("lbl_scatterYRange")
        self.layout_pltGrid.addWidget(self.lbl_scatterYRange, 6, 0, 1, 1)
        self.cmd_savePlot = QtWidgets.QCommandLinkButton(self.formLayoutWidget_2)
        self.cmd_savePlot.setObjectName("cmd_savePlot")
        self.layout_pltGrid.addWidget(self.cmd_savePlot, 9, 1, 1, 2)
        self.check_excMisc = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.check_excMisc.setObjectName("check_excMisc")
        self.layout_pltGrid.addWidget(self.check_excMisc, 2, 2, 1, 1)
        self.cbo_catSelectorPlotting = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.cbo_catSelectorPlotting.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbo_catSelectorPlotting.setObjectName("cbo_catSelectorPlotting")
        self.cbo_catSelectorPlotting.addItem("")
        self.layout_pltGrid.addWidget(self.cbo_catSelectorPlotting, 1, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.layout_pltGrid.addWidget(self.label_6, 1, 0, 1, 1)
        self.lbl_excCats = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_excCats.setObjectName("lbl_excCats")
        self.layout_pltGrid.addWidget(self.lbl_excCats, 2, 0, 1, 1)
        self.check_excUnclassified = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.check_excUnclassified.setObjectName("check_excUnclassified")
        self.layout_pltGrid.addWidget(self.check_excUnclassified, 2, 1, 1, 1)
        self.lbl_optionSavePlot = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_optionSavePlot.setObjectName("lbl_optionSavePlot")
        self.layout_pltGrid.addWidget(self.lbl_optionSavePlot, 9, 0, 1, 1)
        self.check_annotateOutliers = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.check_annotateOutliers.setObjectName("check_annotateOutliers")
        self.layout_pltGrid.addWidget(self.check_annotateOutliers, 4, 1, 1, 1)
        self.lbl_scatterMarker = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_scatterMarker.setObjectName("lbl_scatterMarker")
        self.layout_pltGrid.addWidget(self.lbl_scatterMarker, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.layout_pltGrid.addWidget(self.label_5, 4, 0, 1, 1)
        self.date_highRange = QtWidgets.QDateEdit(self.formLayoutWidget_2)
        self.date_highRange.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.date_highRange.setObjectName("date_highRange")
        self.layout_pltGrid.addWidget(self.date_highRange, 7, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.layout_pltGrid.addWidget(self.label_4, 8, 0, 1, 1)
        self.cmd_plotData = QtWidgets.QCommandLinkButton(self.formLayoutWidget_2)
        self.cmd_plotData.setObjectName("cmd_plotData")
        self.layout_pltGrid.addWidget(self.cmd_plotData, 8, 1, 1, 2)
        self.cbo_markerType = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.cbo_markerType.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbo_markerType.setObjectName("cbo_markerType")
        self.cbo_markerType.addItem("")
        self.cbo_markerType.addItem("")
        self.cbo_markerType.addItem("")
        self.cbo_markerType.addItem("")
        self.layout_pltGrid.addWidget(self.cbo_markerType, 5, 1, 1, 1)
        self.cbo_markerColor = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.cbo_markerColor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbo_markerColor.setObjectName("cbo_markerColor")
        self.cbo_markerColor.addItem("")
        self.cbo_markerColor.addItem("")
        self.cbo_markerColor.addItem("")
        self.cbo_markerColor.addItem("")
        self.cbo_markerColor.addItem("")
        self.cbo_markerColor.addItem("")
        self.cbo_markerColor.addItem("")
        self.layout_pltGrid.addWidget(self.cbo_markerColor, 5, 2, 1, 1)
        self.txt_yLow = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txt_yLow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_yLow.setObjectName("txt_yLow")
        self.layout_pltGrid.addWidget(self.txt_yLow, 6, 1, 1, 1)
        self.txt_yHigh = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txt_yHigh.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_yHigh.setObjectName("txt_yHigh")
        self.layout_pltGrid.addWidget(self.txt_yHigh, 6, 2, 1, 1)
        self.check_addMedian = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.check_addMedian.setObjectName("check_addMedian")
        self.layout_pltGrid.addWidget(self.check_addMedian, 4, 2, 1, 1)
        self.wdg_plot = QtWidgets.QWidget(Form)
        self.wdg_plot.setGeometry(QtCore.QRect(650, 440, 561, 261))
        self.wdg_plot.setAutoFillBackground(False)
        self.wdg_plot.setStyleSheet("background-color: rgb(255, 255, 255, 0);")
        self.wdg_plot.setObjectName("wdg_plot")
        self.formLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 610, 621, 133))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.form_info = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.form_info.setContentsMargins(0, 0, 0, 0)
        self.form_info.setObjectName("form_info")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.form_info.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.form_info.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lbl_dateRange = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_dateRange.setText("")
        self.lbl_dateRange.setObjectName("lbl_dateRange")
        self.form_info.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_dateRange)
        self.lbl_10 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_10.setStyleSheet("")
        self.lbl_10.setObjectName("lbl_10")
        self.form_info.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_10)
        self.lbl_fixedExpRatio = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_fixedExpRatio.setText("")
        self.lbl_fixedExpRatio.setObjectName("lbl_fixedExpRatio")
        self.form_info.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_fixedExpRatio)
        self.lbl_11 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_11.setStyleSheet("")
        self.lbl_11.setObjectName("lbl_11")
        self.form_info.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_11)
        self.lbl_savingsRatio = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_savingsRatio.setText("")
        self.lbl_savingsRatio.setObjectName("lbl_savingsRatio")
        self.form_info.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lbl_savingsRatio)
        self.lbl_user = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_user.setText("")
        self.lbl_user.setObjectName("lbl_user")
        self.form_info.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_user)
        self.lbl_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_14.setStyleSheet("")
        self.lbl_14.setObjectName("lbl_14")
        self.form_info.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_14)
        self.lbl_varExpRatio = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_varExpRatio.setText("")
        self.lbl_varExpRatio.setObjectName("lbl_varExpRatio")
        self.form_info.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_varExpRatio)
        self.lbl_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_15.setStyleSheet("")
        self.lbl_15.setObjectName("lbl_15")
        self.form_info.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_15)
        self.lbl_classRate = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_classRate.setText("")
        self.lbl_classRate.setObjectName("lbl_classRate")
        self.form_info.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lbl_classRate)

        self.retranslateUi(Form)
        self.tab_byMonthYear.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.table_byMonth.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Category"))
        item = self.table_byMonth.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Average (CDN)"))
        item = self.table_byMonth.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Median (CDN)"))
        item = self.table_byMonth.horizontalHeaderItem(3)
        item.setText(_translate("Form", "STD (CDN)"))
        self.tab_byMonthYear.setTabText(self.tab_byMonthYear.indexOf(self.tab), _translate("Form", "Tab 1"))
        item = self.table_byYear.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Category"))
        item = self.table_byYear.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Average (CDN)"))
        item = self.table_byYear.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Median (CDN)"))
        item = self.table_byYear.horizontalHeaderItem(3)
        item.setText(_translate("Form", "STD (CDN)"))
        self.tab_byMonthYear.setTabText(self.tab_byMonthYear.indexOf(self.tab_2), _translate("Form", "Tab 2"))
        self.label.setText(_translate("Form", "  Use the options below to export the data to MS excel file"))
        self.cmd_exportData.setText(_translate("Form", "Export Data"))
        self.label_2.setText(_translate("Form", "  Select a category of expenses to export"))
        self.cbo_catSelectorExporting.setItemText(0, _translate("Form", "All Categories"))
        self.label_3.setText(_translate("Form", "  Select the desired grouping method"))
        self.radio_allTransactions.setText(_translate("Form", "All Transactions"))
        self.radio_byMonth.setText(_translate("Form", "Organized By Month"))
        self.radio_byYear.setText(_translate("Form", "Organized By Year"))
        self.lbl_dateRange_2.setText(_translate("Form", "   Date range"))
        self.lbl_scatterYRange.setWhatsThis(_translate("Form", "<html><head/><body><p>Change number to modify the y-axis in the plot. Leave at 0 if you wish to let the program decide what the range should be</p></body></html>"))
        self.lbl_scatterYRange.setText(_translate("Form", "   y-axis range low (left), high (right)"))
        self.cmd_savePlot.setText(_translate("Form", "Save Plot"))
        self.check_excMisc.setText(_translate("Form", "Exclude Miscellaneous Transfers"))
        self.cbo_catSelectorPlotting.setItemText(0, _translate("Form", "All Categories"))
        self.label_6.setText(_translate("Form", "  Select a category of expenses to export"))
        self.lbl_excCats.setText(_translate("Form", "  Uncheck the boxes to include these categories in plot"))
        self.check_excUnclassified.setText(_translate("Form", "Exclude Unclassified Expenses"))
        self.lbl_optionSavePlot.setText(_translate("Form", "  Do you wish to save the plot as an image?"))
        self.check_annotateOutliers.setText(_translate("Form", "Annotate Outliers"))
        self.lbl_scatterMarker.setText(_translate("Form", "   Scatterplot marker type (left) and color (right)"))
        self.label_5.setText(_translate("Form", "  Include annotations of outliers on plot?"))
        self.cmd_plotData.setText(_translate("Form", "Plot Data"))
        self.cbo_markerType.setItemText(0, _translate("Form", "o"))
        self.cbo_markerType.setItemText(1, _translate("Form", "s"))
        self.cbo_markerType.setItemText(2, _translate("Form", "^"))
        self.cbo_markerType.setItemText(3, _translate("Form", "d"))
        self.cbo_markerColor.setItemText(0, _translate("Form", "green"))
        self.cbo_markerColor.setItemText(1, _translate("Form", "blue"))
        self.cbo_markerColor.setItemText(2, _translate("Form", "purple"))
        self.cbo_markerColor.setItemText(3, _translate("Form", "red"))
        self.cbo_markerColor.setItemText(4, _translate("Form", "yellow"))
        self.cbo_markerColor.setItemText(5, _translate("Form", "orange"))
        self.cbo_markerColor.setItemText(6, _translate("Form", "pink"))
        self.check_addMedian.setText(_translate("Form", "Add median line"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Showing expense results for: </span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">From Date Range</span></p></body></html>"))
        self.lbl_10.setToolTip(_translate("Form", "The fixed cost ratio is defined as the total amount of fixed expenses (rent, mortgage, car, tax, phone/internet) relative to net income. Typical guidelines suggest a FCR of 0.45-0.55.\n"
"If you do not enter data for income, this will report as 0."))
        self.lbl_10.setWhatsThis(_translate("Form", "<html><head/><body><p>The fixed cost ratio is defined as the total amount of fixed expenses (rent, mortgage, car, tax, phone/internet) relative to net income. Typical guidelines suggest a FCR of 0.45-0.55.</p><p>If you do not enter data for income, this will report as 0.</p></body></html>"))
        self.lbl_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Fixed Cost Ratio</span></p></body></html>"))
        self.lbl_11.setToolTip(_translate("Form", "<html><head/><body><p>The savings ratio is defined as the total amount of savings relative to net income. Typical guidelines suggest a savings ratio of 0.1 - 0.25. This value is calculated by the balance of 1 - FCR - VCR - other.</p><p>If you do not enter data for income, this will report as 0.</p></body></html>"))
        self.lbl_11.setWhatsThis(_translate("Form", "<html><head/><body><p>The savings ratio is defined as the total amount of savings relative to net income. Typical guidelines suggest a savings ratio of 0.1 - 0.25. This value is calculated by the balance of 1 - FCR - VCR - other.</p><p>If you do not enter data for income, this will report as 0.</p></body></html>"))
        self.lbl_11.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Savings Ratio</span></p></body></html>"))
        self.lbl_14.setToolTip(_translate("Form", "<html><head/><body><p>The variable cost ratio is defined as the total amount of monthly-variable expenses (social/entertainment, groceries, consumer purchases, etc.) relative to net income. Typical guidelines suggest a VCR of 0.25-0.35.</p><p>If you do not enter data for income, this will report as 0.</p></body></html>"))
        self.lbl_14.setWhatsThis(_translate("Form", "<html><head/><body><p>The variable cost ratio is defined as the total amount of monthly-variable expenses (social/entertainment, groceries, consumer purchases, etc.) relative to net income. Typical guidelines suggest a VCR of 0.25-0.35.</p><p>If you do not enter data for income, this will report as 0.</p></body></html>"))
        self.lbl_14.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Variable Cost Ratio</span></p></body></html>"))
        self.lbl_15.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Classification Rate</span></p></body></html>"))

